name: Docker Image CI

on:
    push:
        tags:
            - "v*"

jobs:
    image-push:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: env setting
              run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/v}" >> $GITHUB_ENV
            - name: Login to GitHub Container Registry
              uses: docker/login-action@v1
              with:
                  registry: ghcr.io
                  username: ${{ github.repository_owner }}
                  password: ${{ secrets.CR_PAT }}
            - name: Build and push
              uses: docker/build-push-action@v4
              with:
                  context: .
                  file: ./Dockerfile
                  platforms: linux/amd64,linux/arm64
                  push: true
                  tags: |
                      ghcr.io/${{ github.repository_owner }}/korean-history-site:latest
                      ghcr.io/${{ github.repository_owner }}/korean-history-site:${{ env.RELEASE_VERSION }}
            - name: Deploy
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.SSH_HOST }}
                  username: ${{ secrets.SSH_USER }}
                  port: ${{ secrets.SSH_PORT }}
                  key: ${{ secrets.SSH_KEY }}
                  script: |
                      docker pull ghcr.io/${{ github.repository_owner }}/korean-history-site:latest
                      docker rm -f korean-history-site
                      docker run -d -p 8888:8000 --name korean-history-site ghcr.io/${{ github.repository_owner }}/korean-history-site:latest
